[profile.default]
solc-version = "0.8.17"
verbosity = 2
optimizer = true
optimizer_runs = 200
# true for stack-too-deep error avoidance,
# off for speedy builds (if it compiles)
via_ir = false


[profile.default.optimizer_details]
constantOptimizer = true
yul = true
